[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  mikalhart/TinyGPSPlus@1.1.0
  adafruit/DHT sensor library@1.4.6
  adafruit/Adafruit Unified Sensor@1.1.15
  bblanchon/ArduinoJson@7.3.1
